[pytest]
addopts = --html=reports/report.html --css=reports/reporte_style.css --self-contained-html

testpaths =
    backend/tests
    frontend/tests


python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
